#!/usr/bin/env python3

import os.path
import http.server
import socketserver
import subprocess

PORT = 44033

basedir = os.path.dirname(__file__)

class HookHandler(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        subprocess.run(['git', '-C', basedir, 'pull'])
        subprocess.run([os.path.join(basedir, 'update')])

        self.send_response(200)
        self.end_headers()

socketserver.TCPServer.allow_reuse_address = True
httpd = socketserver.TCPServer(('', PORT), HookHandler)

try:
    httpd.serve_forever()
except KeyboardInterrupt:
    httpd.shutdown()
