#!/bin/sh
#
# Regenerate all burgerforslag.  Destructive!

set -e # Exit on first error.

cd "$(dirname "$0")"

mkdir -p burgerforslag

inputs=borgerforslag/*.json
outputs=$(echo $inputs | sed 's/bo/bu/g')

./rist_løg -b $inputs $outputs
